### ISSUE TITLE
redis with docker. Example from documentation

### ISSUE THREAD

**Issue by kharandziuk** [ansible/ansible-docker-base#13]
I have a playbook:
```
- name: Configure development machine
  hosts: all
  sudo: True
  tasks:
    - name: set locale
      lineinfile: dest=/etc/default/locale line="LC_ALL=C"

    - name: install curl
      apt: name={{ item }} update_cache=yes
      with_items:
        - git
        - curl
        - libpq-dev
        - python-dev
        - python-psycopg2
        - docker

    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python -

    - pip: name=virtualenv

    - name: Install docker-py
      pip: name=docker-py version=1.1.0

    - pip: requirements=/project/requirements.pip virtualenv=/ENV

    - name: redis container
      docker:
        name: myredis
        image: redis
        command: redis-server --appendonly yes
        state: started
        expose:
            - 6379
```

I'm using Vagrant with Ubuntu 14.04 with 'ubuntu/trusty64'. My vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "./project/", "/project/"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  #config.vm.network :public_network, bridge: 'eth0'
  #config.vm.provider :virtualbox do |vb|
  #  vb.gui = true
  #end

  # config.ssh.forward_agent = true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
```

When I run ansible playbook I receive an error:
```
TASK: [redis container] *******************************************************
failed: [default] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(2, 'No such file or directory')),)
```

**Comment by bocharsky-bw** [comment]
I had same problem too

**Comment by tickletik** [comment]
same problem here, and I"m running OS X

**Comment by ArturSkowronski** [comment]
Same problem here, also on OSX

**Comment by BirgerK** [comment]
Same problem, running on OS X 10.10.3

**Comment by William-Yeh** [comment]
The package name in the playbook shouldn't be `docker`; it should be `docker.io`.

Even you've changed the name to `docker.io`, I'll install a too-old version of Docker (1.0.1). Please follow the official installation guilde at Docker.com ( https://docs.docker.com/installation/ubuntulinux/ ), or just pick a nice role in Ansible Galaxy (e.g., [angstwad.docker_ubuntu](https://galaxy.ansible.com/list#/roles/292) ).

**Comment by bocharsky-bw** [comment]
@William-Yeh Yes, you're right, I think `kharandziuk` should use `docker-io` instead. But I had the same problem when install docker like:

``` yaml
    - name: install docker
      shell: curl -sSL https://get.docker.com/ | sh
      args:
        creates: /usr/bin/docker
```

**Comment by William-Yeh** [comment]
Let me simplify the example.

The `Vagrantfile`:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
```

The `playbook.yml`:

```yaml
- name: Configure development machine
  hosts: all
  sudo: True
  tasks:
    - name: set locale
      lineinfile: dest=/etc/default/locale line="LC_ALL=C"

    - name: install curl
      apt: name={{ item }} update_cache=yes
      with_items:
        - git
        - curl
        - libpq-dev
        - python-dev
        - python-psycopg2

    - name: install docker
      shell: curl -sSL https://get.docker.com/ | sh
      args:
        creates: /usr/bin/docker

    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python -

    - name: Install docker-py
      pip: name=docker-py version=1.1.0

    - name: redis container
      docker:
        name: myredis
        image: redis
        command: redis-server --appendonly yes
        state: started
        expose:
            - 6379
```

Then:

```
$ vagrant up
$ vagrant ssh -c "sudo docker ps"
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
da25211ef621        redis:latest        "/entrypoint.sh redi   3 minutes ago       Up 3 minutes        6379/tcp            myredis
Connection to 127.0.0.1 closed.
```
